# Generated by Django 4.2.6 on 2023-12-19 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "cno",
                    models.CharField(
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="课程号",
                    ),
                ),
                ("cname", models.CharField(max_length=32, verbose_name="课程名")),
                ("ccredit", models.CharField(max_length=32, verbose_name="学分")),
                (
                    "cpno",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.course",
                        verbose_name="先修课",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sdept",
            fields=[
                (
                    "sdeptId",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="学院ID",
                    ),
                ),
                ("sdeptName", models.CharField(max_length=20, verbose_name="学院名")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=12, verbose_name="用户名")),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "sno",
                    models.CharField(
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="学号",
                    ),
                ),
                ("sname", models.CharField(max_length=32, verbose_name="姓名")),
                (
                    "sgender",
                    models.SmallIntegerField(
                        choices=[(1, "男"), (2, "女")], verbose_name="性别"
                    ),
                ),
                ("sage", models.SmallIntegerField(default=18, verbose_name="年龄")),
                (
                    "depart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.sdept",
                        verbose_name="部门",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.CharField(max_length=32, verbose_name="成绩")),
                (
                    "cno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.course",
                    ),
                ),
                (
                    "sno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.student",
                    ),
                ),
            ],
        ),
    ]
