# Generated by Django 4.2.6 on 2023-12-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sc",
            name="grade",
            field=models.SmallIntegerField(verbose_name="成绩"),
        ),
    ]
